#!url=https://raw.githubusercontent.com/hvbstar/devhvb/main/SoundCloud_HVB.sgmodule
#!name=SoundCloudGo+ | Hoàng Văn Bảo (HVB)
#!desc=SoundCloudGo+ Free by HVB
[Script]
SoundCloudGo+=type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/hvbstar/devhvb/main/SoundCloudGoPlus_HVB.js
[MITM]
hostname= %APPEND% api-mobile.soundcloud.com
